// src/lib/components/InitialCard.svelte
<script lang="ts">
	import { sessionStore } from '$lib/stores/session.svelte'

	let username = $state('')
	let sessionCode = $state('')
	let isCreatingSession = $state(true)

	async function handleSubmit() {
		if (isCreatingSession) {
			await sessionStore.createSession(username)
		} else {
			await sessionStore.joinSession(username, sessionCode)
		}
	}

	function handleCodeInput(e: Event) {
		const target = e.target as HTMLInputElement
		sessionCode = target.value.replace(/\D/g, '').slice(0, 4)
	}

	let isDisabled = $derived(!username || (!isCreatingSession && sessionCode.length !== 4))
</script>

<div class="w-full min-h-[100dvh] flex flex-col items-center justify-center px-5 bg-piknik-gradient relative overflow-hidden">
	<!-- Decorative circles -->
	<div class="absolute top-[-80px] right-[-60px] w-64 h-64 bg-white/5 rounded-full"></div>
	<div class="absolute bottom-[20%] left-[-40px] w-40 h-40 bg-white/5 rounded-full"></div>

	<div class="w-full max-w-[390px] page-enter relative z-10">
		<!-- Title above card -->
		<div class="text-center mb-3">
			<h1 class="text-[36px] font-extrabold text-white tracking-tight drop-shadow-lg">PikNik!</h1>
			<p class="text-[15px] mt-1 text-white/80 leading-snug">
				<span class="underline decoration-orange-400 decoration-2 underline-offset-2">Bland</span> ingrediensar,
				<span class="underline decoration-green-400 decoration-2 underline-offset-2">skap</span> oppskrifter,
				<span class="underline decoration-blue-400 decoration-2 underline-offset-2">del</span> med venner!
			</p>
		</div>

		<!-- Mascot area -->
		<div class="flex justify-center mb-4">
			<img
				src="/piknik/walk-groceries-a.gif"
				alt="PikNik maskot"
				class="w-56 h-56 object-contain mascot-float drop-shadow-xl"
			/>
		</div>

		<!-- Card slides up from bottom -->
		<div class="bg-white/95 backdrop-blur-xl rounded-3xl shadow-2xl overflow-hidden bottom-sheet-enter">
			<!-- Form -->
			<div class="px-6 py-7 space-y-4">
				<label class="flex items-center gap-3 cursor-pointer py-1">
					<button
						type="button"
						role="switch"
						aria-checked={isCreatingSession}
						aria-label="Bytt mellom lag okt og bli med i okt"
						class="relative inline-flex h-[31px] w-[51px] items-center rounded-full transition-colors duration-200 flex-shrink-0
							{isCreatingSession ? 'bg-purple-500' : 'bg-gray-300'}"
						onclick={() => (isCreatingSession = !isCreatingSession)}
					>
						<span
							class="inline-block h-[27px] w-[27px] transform rounded-full bg-white shadow-sm transition-transform duration-200
								{isCreatingSession ? 'translate-x-[22px]' : 'translate-x-[2px]'}"
						></span>
					</button>
					<span class="text-[17px] font-bold text-purple-700">
						{isCreatingSession ? 'Lag okt' : 'Bli med i okt'}
					</span>
				</label>

				<input
					type="text"
					bind:value={username}
					placeholder="Brukarnamn"
					class="w-full h-14 px-5 text-[17px] border-2 border-purple-100 rounded-2xl bg-purple-50/50 focus:bg-white focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all"
				/>

				{#if !isCreatingSession}
					<input
						type="text"
						value={sessionCode}
						oninput={handleCodeInput}
						placeholder="0000"
						maxlength={4}
						inputmode="numeric"
						class="w-full h-16 px-4 text-[28px] font-bold border-2 border-purple-100 rounded-2xl bg-purple-50/50 focus:bg-white focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent text-center tracking-[0.4em] transition-all"
					/>
				{/if}

				<button
					onclick={handleSubmit}
					disabled={isDisabled}
					class="w-full h-14 rounded-2xl text-white text-[17px] font-bold transition-all duration-200
						{isDisabled
							? 'bg-gray-300 cursor-not-allowed'
							: 'bg-piknik-gradient shadow-xl shadow-purple-600/30 hover:shadow-2xl active:scale-[0.97]'}"
				>
					{isCreatingSession ? 'Lag okt' : 'Bli med'}
				</button>
			</div>
		</div>
	</div>
</div>

// components/initial-card.tsx
import React, { useState } from 'react'
import Image from 'next/image'
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card"
import { Switch } from "@/components/ui/switch"
import { Label } from "@/components/ui/label"

interface InitialCardProps {
  onJoinSession: (username: string, code: string) => void
  onCreateSession: (username: string) => void
}

export const InitialCard: React.FC<InitialCardProps> = ({ onJoinSession, onCreateSession }) => {
  const [username, setUsername] = useState('')
  const [sessionCode, setSessionCode] = useState('')
  const [isCreatingSession, setIsCreatingSession] = useState(true)

  return (
    <Card className="w-full max-w-md mx-auto mt-20 bg-white relative">
      <CardHeader className="flex flex-col items-center">
        <Image src="/piknik-maskot.png" alt="PikNik Logo" width={200} height={200} />
        <CardTitle className="text-2xl font-bold text-center text-purple-600 mt-4">Velkomen til PikNik!</CardTitle>
        <p className="text-center mt-2">
          <span className="underline decoration-purple-500">Bland</span> ingredienser, 
          <span className="underline decoration-green-500">skap</span> oppskrifter, 
          <span className="underline decoration-blue-500">del</span> med venner!
        </p>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          <div className="flex items-center space-x-2">
            <Switch id="session-mode" checked={isCreatingSession} onCheckedChange={() => setIsCreatingSession(prev => !prev)} />
            <Label htmlFor="session-mode" className="text-lg font-medium text-purple-700">{isCreatingSession ? 'Lag økt' : 'Bli med i økt'}</Label>
          </div>
          <Input id="username" value={username} onChange={(e) => setUsername(e.target.value)} placeholder="Skriv inn brukarnamnet ditt" className="mt-1 bg-white" />
          {!isCreatingSession && <Input id="sessionCode" value={sessionCode} onChange={(e) => setSessionCode(e.target.value.replace(/\D/g, '').slice(0, 4))} placeholder="Skriv inn 4-sifra kode" className="mt-1 bg-white" maxLength={4} />}
        </div>
      </CardContent>
      <CardFooter>
        <Button onClick={() => isCreatingSession ? onCreateSession(username) : onJoinSession(username, sessionCode)} 
                disabled={!username || (!isCreatingSession && sessionCode.length !== 4)}
                className="w-full bg-purple-500 hover:bg-purple-600 text-white">
          {isCreatingSession ? 'Lag økt' : 'Bli med i økt'}
        </Button>
      </CardFooter>
    </Card>
  )
}
