// components/recipe-history.tsx
import React, { useState, useEffect } from 'react'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Button } from "@/components/ui/button"
import { Oppskrift, Ingrediens } from './piknik'
import { ArrowLeft, ChevronRight } from 'lucide-react'

interface RecipeHistoryProps {
  isOpen: boolean
  onClose: () => void
  recipes: Oppskrift[]
  onSelectRecipe: (recipe: Oppskrift) => void
}

export function RecipeHistory({ isOpen, onClose, recipes, onSelectRecipe }: RecipeHistoryProps) {
  const [selectedRecipe, setSelectedRecipe] = useState<Oppskrift | null>(null)

  useEffect(() => {
    console.log('RecipeHistory rendered with recipes:', recipes)
  }, [recipes])

  const handleSelectRecipe = (recipe: Oppskrift) => {
    setSelectedRecipe(recipe)
  }

  const handleReturn = () => {
    setSelectedRecipe(null)
  }

  const handleUseRecipe = () => {
    if (selectedRecipe) {
      onSelectRecipe(selectedRecipe)
      onClose()
    }
  }

  const formatIngredient = (ingrediens: Ingrediens) => {
    return `${ingrediens.mengde} ${ingrediens.eining} ${ingrediens.namn}`
  }

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>
            {selectedRecipe ? (
              <div className="flex items-center">
                <Button variant="ghost" size="sm" onClick={handleReturn} className="mr-2 p-0">
                  <ArrowLeft className="h-4 w-4" />
                </Button>
                {selectedRecipe.tittel}
              </div>
            ) : (
              'Oppskrifthistorikk'
            )}
          </DialogTitle>
        </DialogHeader>
        <ScrollArea  className="h-[400px] w-full rounded-md border p-4">
          {selectedRecipe ? (
            <div>
              <p className="text-sm text-gray-500 mb-2">
                {new Date(selectedRecipe.dato).toLocaleString('no-NO', { 
                  year: 'numeric', 
                  month: 'long', 
                  day: 'numeric', 
                  hour: '2-digit', 
                  minute: '2-digit' 
                })}
              </p>
              <p className="text-sm text-gray-700 mb-4">{selectedRecipe.skildring}</p>
              <h4 className="font-semibold mb-2">Ingredienser:</h4>
              <ul className="list-disc list-inside mb-4">
                {selectedRecipe.ingrediensar.map((ingrediens, index) => (
                  <li key={index} className="text-sm">
                    {formatIngredient(ingrediens)}
                  </li>
                ))}
              </ul>
              <h4 className="font-semibold mb-2">Fremgangsmåte:</h4>
              <ol className="list-decimal list-inside mb-4">
                {selectedRecipe.steg.map((steg, index) => (
                  <li key={index} className="text-sm mb-2">{steg}</li>
                ))}
              </ol>
              <Button onClick={handleUseRecipe} className="w-full">Bruk denne oppskriften</Button>
            </div>
          ) : recipes.length === 0 ? (
            <p className="text-center text-gray-500">Ingen oppskrifter ennå.</p>
          ) : (
            recipes.map((recipe, index) => (
              <div 
                key={recipe.id || index} 
                className="mb-2 p-2 border rounded-lg shadow-sm hover:shadow-md transition-shadow cursor-pointer flex justify-between items-center"
                onClick={() => handleSelectRecipe(recipe)}
              >
                <div>
                  <h3 className="font-semibold text-sm mb-1">{recipe.tittel}</h3>
                  <p className="text-xs text-gray-500">
                    {new Date(recipe.dato).toLocaleString('no-NO', { 
                      year: 'numeric', 
                      month: 'long', 
                      day: 'numeric', 
                      hour: '2-digit', 
                      minute: '2-digit' 
                    })}
                  </p>
                </div>
                <ChevronRight className="h-4 w-4 text-gray-400" />
              </div>
            ))
          )}
        </ScrollArea>
      </DialogContent>
    </Dialog>
  )
}

// src/lib/components/RecipeHistory.svelte
<script lang="ts">
	import type { Oppskrift, Ingrediens } from '$lib/types'
	import { recipesStore } from '$lib/stores/recipes.svelte'
	import { ArrowLeft, ChevronRight } from 'lucide-svelte'

	let {
		isOpen,
		onClose,
		onSelectRecipe
	}: {
		isOpen: boolean
		onClose: () => void
		onSelectRecipe: (recipe: Oppskrift) => void
	} = $props()

	let selectedRecipe = $state<Oppskrift | null>(null)

	function formatIngredient(ingrediens: Ingrediens) {
		return `${ingrediens.mengde} ${ingrediens.eining} ${ingrediens.namn}`
	}

	function handleSelectRecipe(recipe: Oppskrift) {
		selectedRecipe = recipe
	}

	function handleReturn() {
		selectedRecipe = null
	}

	function handleUseRecipe() {
		if (selectedRecipe) {
			onSelectRecipe(selectedRecipe)
			selectedRecipe = null
			onClose()
		}
	}

	function handleClose() {
		selectedRecipe = null
		onClose()
	}

	function getRelativeTime(dateStr: string): string {
		const now = Date.now()
		const date = new Date(dateStr).getTime()
		const diffMs = now - date
		const diffMin = Math.floor(diffMs / 60000)
		if (diffMin < 1) return 'Akkurat no'
		if (diffMin < 60) return `${diffMin} min sidan`
		const diffHours = Math.floor(diffMin / 60)
		if (diffHours < 24) return `${diffHours} t sidan`
		const diffDays = Math.floor(diffHours / 24)
		return `${diffDays} d sidan`
	}
</script>

{#if isOpen}
	<!-- svelte-ignore a11y_no_static_element_interactions -->
	<div
		class="fixed inset-0 bg-black/50 flex items-end sm:items-center justify-center z-50 blend-overlay"
		onkeydown={(e) => e.key === 'Escape' && handleClose()}
	>
		<!-- svelte-ignore a11y_click_events_have_key_events -->
		<div class="absolute inset-0" onclick={handleClose}></div>
		<div
			class="relative w-full sm:max-w-md bg-white rounded-t-3xl sm:rounded-3xl bottom-sheet-enter safe-bottom overflow-hidden"
			style="max-height: 85vh"
		>
			<!-- Drag handle -->
			<div class="flex justify-center pt-3 pb-1 sm:hidden">
				<div class="w-10 h-1 bg-gray-200 rounded-full"></div>
			</div>

			<!-- Header -->
			<div class="flex items-center px-6 py-4 border-b border-purple-100">
				{#if selectedRecipe}
					<button class="p-1 mr-2 rounded-xl hover:bg-purple-50 transition-colors" onclick={handleReturn}>
						<ArrowLeft class="h-5 w-5 text-purple-600" />
					</button>
					<h2 class="text-lg font-bold truncate text-gray-900">{selectedRecipe.tittel}</h2>
				{:else}
					<img src="/piknik/idle-mushroom.gif" alt="Historikk" class="w-8 h-8 object-contain mr-2" />
					<h2 class="text-lg font-bold text-gray-900">Oppskrifthistorikk</h2>
				{/if}
				<button class="p-2 rounded-full hover:bg-purple-50 ml-auto transition-colors" onclick={handleClose}>
					✕
				</button>
			</div>

			<!-- Content -->
			<div class="px-6 py-4 overflow-y-auto" style="max-height: calc(85vh - 80px)">
				{#if selectedRecipe}
					<p class="text-sm text-purple-500 font-medium mb-2">
						{getRelativeTime(selectedRecipe.dato)}
					</p>
					<p class="text-[15px] text-gray-700 mb-5">{selectedRecipe.skildring}</p>

					<h4 class="text-[13px] font-bold uppercase tracking-wider text-purple-600 mb-3">Ingrediensar</h4>
					<div class="grid grid-cols-2 gap-2 mb-5">
						{#each selectedRecipe.ingrediensar as ingrediens}
							<div class="bg-purple-50 rounded-xl p-3">
								<span class="text-sm font-medium">{ingrediens.namn}</span>
								<span class="text-xs text-purple-500 block">{ingrediens.mengde} {ingrediens.eining}</span>
							</div>
						{/each}
					</div>

					<h4 class="text-[13px] font-bold uppercase tracking-wider text-purple-600 mb-3">Framgangsmåte</h4>
					<ol class="space-y-3 mb-5">
						{#each selectedRecipe.steg as steg, i}
							<li class="flex gap-3">
								<span class="flex-shrink-0 w-7 h-7 rounded-full bg-purple-500 text-white text-xs font-bold flex items-center justify-center">
									{i + 1}
								</span>
								<span class="text-sm leading-relaxed pt-0.5">{steg}</span>
							</li>
						{/each}
					</ol>

					<button
						class="w-full py-3.5 rounded-2xl bg-piknik-gradient text-white font-bold shadow-lg shadow-purple-500/20 hover:shadow-xl transition-all"
						onclick={handleUseRecipe}
					>
						Bruk denne oppskrifta
					</button>
				{:else if recipesStore.recipeHistory.length === 0}
					<div class="flex flex-col items-center justify-center py-10 gap-3">
						<img src="/piknik/sleep-a.gif" alt="Ingen oppskrifter" class="w-28 h-28 object-contain mascot-float" />
						<p class="text-[15px] font-medium text-gray-400">Ingen oppskrifter enno</p>
					</div>
				{:else}
					<div class="space-y-2.5">
						{#each recipesStore.recipeHistory as recipe, i}
							<button
								type="button"
								class="w-full p-4 bg-white border border-purple-100 rounded-2xl shadow-sm hover:shadow-md transition-all flex items-center gap-3 text-left tap-feedback ingredient-enter"
								style="animation-delay: {i * 60}ms"
								onclick={() => handleSelectRecipe(recipe)}
							>
								<div class="w-1 h-10 rounded-full bg-piknik-gradient flex-shrink-0"></div>
								<div class="min-w-0 flex-1">
									<h3 class="font-bold text-[15px] mb-0.5 truncate text-gray-900">{recipe.tittel}</h3>
									<p class="text-[12px] text-purple-500 font-medium">{getRelativeTime(recipe.dato)}</p>
								</div>
								<ChevronRight class="h-4 w-4 text-purple-400 flex-shrink-0" />
							</button>
						{/each}
					</div>
				{/if}
			</div>
		</div>
	</div>
{/if}
