// components/recipe-modal.tsx
import React from 'react'
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Download, X } from 'lucide-react'

interface Ingrediens {
  namn: string
  mengde: number
  eining: string
}

interface Oppskrift {
  tittel: string
  skildring: string
  ingrediensar: Ingrediens[]
  steg: string[]
}

interface RecipeModalProps {
  oppskrift: Oppskrift
  onClose: () => void
  toPDF: () => void
  targetRef: React.RefObject<HTMLDivElement>
}

export const RecipeModal: React.FC<RecipeModalProps> = ({ oppskrift, onClose, toPDF, targetRef }) => {
  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
      <Card className="w-full max-w-md h-[90vh] flex flex-col bg-white">
        <CardHeader className="flex-shrink-0">
          <div className="flex items-center justify-between">
            <CardTitle className="pr-8 truncate">{oppskrift.tittel}</CardTitle>
            <div className="flex space-x-2 flex-shrink-0">
              <Button variant="ghost" size="icon" onClick={() => setTimeout(() => toPDF(), 100)}>
                <Download className="h-4 w-4" />
              </Button>
              <Button variant="ghost" size="icon" onClick={onClose}>
                <X className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </CardHeader>
        <ScrollArea className="flex-grow">
          <CardContent ref={targetRef} className="p-6 max-w-3xl mx-auto">
            <h2 className="text-2xl font-bold mb-4">{oppskrift.tittel}</h2>
            <p className="mb-6">{oppskrift.skildring}</p>
            <h3 className="text-xl font-semibold mb-2">Ingrediensar</h3>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Ingrediens</TableHead>
                  <TableHead>Mengde</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {oppskrift.ingrediensar.map((ing, index) => (
                  <TableRow key={index}>
                    <TableCell>{ing.namn}</TableCell>
                    <TableCell>{ing.mengde} {ing.eining}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
            <h3 className="text-xl font-semibold mt-6 mb-2">Framgangsmåte</h3>
            <ol className="list-decimal list-inside">
              {oppskrift.steg.map((steg, index) => (
                <li key={index} className="mb-2">{steg}</li>
              ))}
            </ol>
          </CardContent>
        </ScrollArea>
      </Card>
    </div>
  )
}

// src/lib/components/RecipeModal.svelte
<script lang="ts">
	import type { Oppskrift } from '$lib/types'
	import { X } from 'lucide-svelte'

	let { oppskrift, onClose }: { oppskrift: Oppskrift; onClose: () => void } = $props()
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
	class="fixed inset-0 bg-black/50 flex items-end justify-center z-50 blend-overlay"
	onkeydown={(e) => e.key === 'Escape' && onClose()}
>
	<!-- svelte-ignore a11y_click_events_have_key_events -->
	<div class="absolute inset-0" onclick={onClose}></div>
	<div
		class="relative w-full max-w-md bg-white rounded-t-3xl bottom-sheet-enter safe-bottom overflow-hidden"
		style="max-height: 90vh"
	>
		<!-- Header -->
		<div class="bg-piknik-gradient-card px-5 pt-5 pb-5 relative">
			<button class="absolute top-4 right-4 p-2 rounded-full bg-white/20 text-white tap-feedback" onclick={onClose}>
				<X class="h-5 w-5" />
			</button>
			<h2 class="text-[28px] font-black text-white leading-tight pr-10">{oppskrift.tittel}</h2>
			<p class="text-white/80 text-[15px] font-medium mt-1">{oppskrift.skildring}</p>
		</div>

		<!-- Content -->
		<div class="overflow-y-auto scroll-area" style="max-height: calc(90vh - 140px)">
			<!-- Ingredients as compact chips -->
			<div class="px-5 py-4">
				<div class="flex flex-wrap gap-2 stagger-in" style="animation-delay: 100ms">
					{#each oppskrift.ingrediensar as ing}
						<span class="inline-flex items-center gap-1 px-3 py-1.5 bg-purple-100 rounded-full text-[14px] font-bold text-purple-700">
							{ing.mengde} {ing.eining} {ing.namn}
						</span>
					{/each}
				</div>
			</div>

			<!-- Steps -->
			<div class="px-5 pb-8">
				<ol class="space-y-4 stagger-in" style="animation-delay: 200ms">
					{#each oppskrift.steg as steg, index}
						<li class="flex gap-3">
							<div class="flex-shrink-0 w-8 h-8 rounded-full bg-purple-500 text-white text-[14px] font-black flex items-center justify-center">
								{index + 1}
							</div>
							<p class="text-[15px] leading-relaxed text-gray-800 font-medium pt-1">{steg}</p>
						</li>
					{/each}
				</ol>
			</div>
		</div>
	</div>
</div>
